import {
  BootstrapIcon,
  CssIcon,
  DockerIcon,
  ExpressIcon,
  GitIcon,
  HtmlIcon,
  JsIcon,
  JWTIcon,
  MongoDBIcon,
  NextIcon,
  NodeJsIcon,
  PostmanIcon,
  ReactIcon,
  ShadcnIcon,
  Supabase,
  TailwindCssIcon,
  TsIcon,
  VercelIcon,
} from "@/components/icons/icons";

import type { TechStack } from "../types/tech-stack";

export const TECH_STACK: TechStack[] = [
  {
    key: "html",
    title: "HTML",
    href: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    icon: <HtmlIcon />,
    categories: ["Frontend"],
  },
  {
    key: "css",
    title: "CSS",
    href: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    icon: <CssIcon />,
    categories: ["Frontend"],
  },
  {
    key: "javascript",
    title: "JavaScript",
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    icon: <JsIcon />,
    categories: ["Language"],
  },
  {
    key: "typescript",
    title: "TypeScript",
    href: "https://www.typescriptlang.org",
    icon: <TsIcon />,
    categories: ["Language"],
  },
  {
    key: "react",
    title: "React",
    href: "https://react.dev",
    icon: <ReactIcon />,
    categories: ["Frontend"],
  },
  {
    key: "nextjs",
    title: "Next.js",
    href: "https://nextjs.org",
    icon: <NextIcon />,
    categories: ["Frontend"],
  },
  {
    key: "tailwindcss",
    title: "Tailwind CSS",
    href: "https://tailwindcss.com",
    icon: <TailwindCssIcon />,
    categories: ["Frontend"],
  },
  {
    key: "bootstrap",
    title: "Bootstrap",
    href: "https://getbootstrap.com",
    icon: <BootstrapIcon />,
    categories: ["Frontend"],
  },
  {
    key: "supabase",
    title: "Supabase",
    href: "https://supabase.com",
    icon: <Supabase />,
    categories: ["Backend"],
  },
  {
    key: "shadcn-ui",
    title: "shadcn/ui",
    href: "https://ui.shadcn.com",
    icon: <ShadcnIcon />,
    categories: ["Frontend"],
  },
  {
    key: "nodejs",
    title: "Node.js",
    href: "https://nodejs.org",
    icon: <NodeJsIcon />,
    categories: ["Backend & Database"],
  },
  {
    key: "express",
    title: "Express",
    href: "https://expressjs.com",
    icon: <ExpressIcon />,
    categories: ["Backend & Database"],
  },
  {
    key: "jwt",
    title: "JWT",
    href: "https://jwt.io",
    icon: <JWTIcon />,
    categories: ["Backend & Database"],
  },
  {
    key: "mongodb",
    title: "MongoDB",
    href: "https://www.mongodb.com",
    icon: <MongoDBIcon />,
    categories: ["Backend & Database"],
  },
  {
    key: "git",
    title: "Git",
    href: "https://git-scm.com",
    icon: <GitIcon />,
    categories: ["Workflow & AI"],
  },

  {
    key: "docker",
    title: "Docker",
    href: "https://www.docker.com",
    icon: <DockerIcon />,
    categories: ["Workflow & AI"],
  },
  {
    key: "postman",
    title: "Postman",
    href: "https://www.postman.com",
    icon: <PostmanIcon />,
    categories: ["Workflow & AI"],
  },
  {
    key: "vercel",
    title: "Vercel",
    href: "https://vercel.com",
    icon: <VercelIcon />,
    categories: ["Workflow & AI"],
  },
];
